// src/react/details-group/index.ts
import * as React from 'react';
import { createComponent } from '@lit/react';
import Component from '../../components/details-group/details-group.component.js';

const tagName = 'sl-details-group';
Component.define('sl-details-group');

/**
 * @since 2.0
 * @status stable
 * @viur 0.5
 *
 * @slot - The default slot.
 *
 * @cssproperty --details-gap - The gap between the detail boxes.
 */
const reactWrapper = createComponent({
  tagName,
  elementClass: Component,
  react: React,
  events: {},
  displayName: 'SlDetailsGroup'
});

export default reactWrapper;

// src/components/details-group/details-group.component.ts
import { html } from 'lit';
import { customElement, queryAssignedNodes } from 'lit/decorators.js';
import styles from './details-group.styles';
import ShoelaceElement from '../../internal/shoelace-element.js';

/**
 * @since 2.0
 * @status stable
 * @viur 0.5
 *
 * @slot - The default slot.
 *
 * @cssproperty --details-gap - The gap between the detail boxes.
 */
@customElement('sl-details-group')
export default class SlDetailsGroup extends ShoelaceElement {
  static styles = styles;

  @queryAssignedNodes('', true)
  currentSlotNodes: any;

  hasChanged() {
    this.registerDetails();
  }

  handleSlotChange() {
    this.registerDetails();
  }

  registerDetails() {
    let detailsList = Array.prototype.filter.call(
      this.currentSlotNodes,
      (node: any) => node.nodeType == Node.ELEMENT_NODE
    );

    if (detailsList) {
      for (const details of detailsList) {
        details.addEventListener('sl-show', (event: Event) => {
          [...detailsList].map(details => (details.open = event.target === details));
        });
      }
    }
  }

  render() {
    return html` <slot @slotchange=${this.handleSlotChange}> </slot> `;
  }
}

declare global {
  interface HTMLElementTagNameMap {
    'sl-details-group': SlDetailsGroup;
  }
}
